# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 886a3a8d3d662764307a06a41679da6e8ea94f89f781f9982b6b9281a2905e2d80a2c9e2453524fada4c5a906e0ba5b9967798165a2bc9e92675ca362f840417

test:
  secret_key_base: b3f4b3913398283ea9b77d26d8377b1752aa7d5e3b52da55343d89af296d89b17715bde89690a53ce641a4b8265506e801a9c9dd735bdfc8928369abb49e7029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
